# Vercel-specific configuration overrides

# -- SERVER CONFIGURATION --
# In Vercel, the server must listen for incoming requests.
listen: true

# -- BROWSER LAUNCH CONFIGURATION --
# Disable browser launch in a headless environment.
browserLaunch:
  enabled: false

# -- LOGGING CONFIGURATION --
# Disable file-based access logging. Logs will go to stdout/stderr.
logging:
  enableAccessLog: false

# -- BACKUP CONFIGURATION --
# Disable file-based backups. Data is persisted in KV store.
backups:
  chat:
    enabled: false

# -- THUMBNAILING CONFIGURATION --
# Disable thumbnail generation which writes to disk.
thumbnails:
  enabled: false

# -- PERFORMANCE-RELATED CONFIGURATION --
# Disable disk cache.
performance:
  useDiskCache: false

# -- EXTENSIONS CONFIGURATION --
# Disable automatic model downloads.
extensions:
  models:
    autoDownload: false